"use client";
import { useCallback, useRef, useState } from 'react';
import { compressToTargetSize, formatBytes, CompressResult } from '@/lib/compress';
import { saveHistory } from '@/lib/history';

export type Requirement = { id: string; title: string; type: 'Photo'|'Signature'|'Thumb'|'Declaration'|'Document'; minKB?: number; maxKB?: number; width?: number; height?: number; format: string; note?: string; source?: string };

export const REQUIREMENTS: Requirement[] = [
 {id:'ssc-cgl-photo',title:'SSC CGL 2026 • Live Photo',type:'Photo',format:'Live capture',note:'Photo is captured on the official portal. Real Image Resizer can prepare/check uploaded files but cannot replace live capture.',source:'SSC CGL 2026 official notice'},
 {id:'ssc-cgl-sign',title:'SSC CGL 2026 • Signature',type:'Signature',minKB:10,maxKB:20,format:'JPG/JPEG',width:4,height:2,note:'About 4 × 2 cm',source:'SSC CGL 2026 official notice'},
 {id:'upsc-photo',title:'UPSC • Photo',type:'Photo',maxKB:300,format:'JPG',note:'Some UPSC recruitments have different requirements. Verify the selected notice.',source:'UPSC official notice'},
 {id:'upsc-sign',title:'UPSC • Signature',type:'Signature',maxKB:300,minKB:50,format:'JPG',source:'UPSC official notice'},
 {id:'neet-photo',title:'NEET UG 2026 • Photograph',type:'Photo',minKB:10,maxKB:200,format:'JPG/JPEG',note:'Recent scanned passport-size photo; live photo is also captured in the application.',source:'NEET UG 2026 Information Bulletin'},
 {id:'neet-sign',title:'NEET UG • Signature',type:'Signature',format:'JPG/JPEG',note:'Use the current NTA bulletin for the exact signature limit.',source:'NTA official'},
 {id:'cuet-photo',title:'CUET UG 2026 • Photograph',type:'Photo',minKB:10,maxKB:200,format:'JPG/JPEG',note:'80% face including ears, white background; live photo also required.',source:'CUET UG 2026 Information Bulletin'},
 {id:'cuet-sign',title:'CUET UG 2026 • Signature',type:'Signature',minKB:10,maxKB:50,format:'JPG/JPEG',source:'CUET UG 2026 Information Bulletin'},
 {id:'ibps-photo',title:'IBPS 2026 • Photograph',type:'Photo',minKB:20,maxKB:50,format:'JPEG',width:200,height:230,note:'Preferred 200 × 230 px; live photograph is also captured.',source:'IBPS 2026–27 calendar/guidelines'},
 {id:'ibps-sign',title:'IBPS 2026 • Signature',type:'Signature',minKB:10,maxKB:20,format:'JPEG',width:140,height:60,source:'IBPS 2026–27 guidelines'},
 {id:'ibps-thumb',title:'IBPS 2026 • Left Thumb',type:'Thumb',minKB:20,maxKB:50,format:'JPG/JPEG',width:240,height:240,note:'Preferred 240 × 240 px',source:'IBPS 2026–27 guidelines'},
 {id:'ibps-declaration',title:'IBPS 2026 • Handwritten Declaration',type:'Declaration',minKB:50,maxKB:100,format:'JPEG',width:800,height:400,source:'IBPS 2026–27 guidelines'},
 {id:'custom',title:'Custom Requirement',type:'Photo',format:'JPG/JPEG'}
];

const QUICK = REQUIREMENTS.filter(r=>['ssc-cgl-sign','neet-photo','cuet-photo','cuet-sign','ibps-photo','ibps-sign'].includes(r.id));

type Stage='idle'|'ready'|'compressing'|'done'|'error';

export default function Tool(){
 const [file,setFile]=useState<File|null>(null); const [url,setUrl]=useState<string|null>(null); const [req,setReq]=useState<Requirement>(REQUIREMENTS[4]);
 const [minKB,setMinKB]=useState(10); const [maxKB,setMaxKB]=useState(200); const [width,setWidth]=useState<number|undefined>(); const [height,setHeight]=useState<number|undefined>();
 const [stage,setStage]=useState<Stage>('idle'); const [result,setResult]=useState<CompressResult|null>(null); const [error,setError]=useState(''); const input=useRef<HTMLInputElement>(null);
 const apply=(r:Requirement)=>{setReq(r);setMinKB(r.minKB??0);setMaxKB(r.maxKB??500);setWidth(r.width);setHeight(r.height);setResult(null);setStage(file?'ready':'idle');};
 const handle=useCallback(async(f?:File|null)=>{if(!f)return;const n=f.name.toLowerCase();if(!f.type.startsWith('image/')&&!n.endsWith('.heic')&&!n.endsWith('.heif')){setError('Please choose JPG, PNG, WebP or HEIC/HEIF.');return;}setError('');setFile(f);setUrl(URL.createObjectURL(f));setResult(null);setStage('ready');},[]);
 const run=async()=>{if(!file)return;if(minKB&&maxKB&&minKB>maxKB){setError('Minimum KB cannot be greater than maximum KB.');return;}setStage('compressing');setError('');try{const res=await compressToTargetSize(file,(maxKB||500)*1024,{exactWidth:width,exactHeight:height});setResult(res);setStage('done');
   try { await saveHistory({ id: crypto.randomUUID(), name: `realimageresizer-${req.id}-${Date.now()}.jpg`, requirementId: req.id, requirementTitle: req.title, type: req.type, originalSize: file.size, outputSize: res.sizeBytes, width: res.width, height: res.height, createdAt: Date.now(), blob: res.blob }); window.dispatchEvent(new Event('realimageresizer:history-updated')); } catch (historyError) { console.warn('History could not be saved', historyError); }}catch(e){console.error(e);setError('Could not process this file. If it is HEIC, make sure the latest dependencies are installed.');setStage('ready');}};
 const reset=()=>{setFile(null);setUrl(null);setResult(null);setStage('idle');setError('');if(input.current)input.current.value='';};
 const kb=result?result.sizeBytes/1024:0; const valid=result?kb>=(minKB||0)-0.01 && kb<=(maxKB||Infinity)+0.01:true;
 return <div className="w-full max-w-[760px] mx-auto">
  <div className="mb-5 text-left"><p className="text-sm font-semibold mb-2">Popular Indian student requirements</p><div className="flex flex-wrap gap-2">{QUICK.map(r=><button key={r.id} onClick={()=>apply(r)} className={`rounded-full border px-3 py-2 text-xs font-semibold ${req.id===r.id?'bg-accent text-white border-accent':'bg-white border-black/10 hover:border-accent/40'}`}>{r.title.split(' • ')[0]}</button>)}</div></div>
  {stage==='idle'&&<div onClick={()=>input.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();handle(e.dataTransfer.files?.[0])}} className="cursor-pointer rounded-2xl border-2 border-dashed border-black/15 bg-white/70 px-6 py-16 text-center hover:border-accent/60 transition"><input ref={input} type="file" accept="image/*,.heic,.heif" className="hidden" onChange={e=>handle(e.target.files?.[0])}/><div className="mx-auto mb-4 w-14 h-14 rounded-full bg-accentSoft flex items-center justify-center text-2xl">📸</div><p className="font-semibold">Photo ya signature upload karo</p><p className="text-sm opacity-50 mt-1">JPG · PNG · WebP · HEIC/HEIF · processing device par hi hoti hai</p></div>}
  {error&&<p className="mt-3 text-sm text-red-600 text-center">{error}</p>}
  {(stage==='ready'||stage==='compressing')&&file&&<div className="rounded-2xl border border-black/10 bg-white/80 p-6 text-left">
   <div className="flex items-center gap-3 mb-6"><img src={url!} className="w-16 h-16 rounded-lg object-cover border border-black/10" alt="Selected"/><div className="min-w-0"><p className="font-medium text-sm truncate">{file.name}</p><p className="text-xs opacity-50">{formatBytes(file.size)}</p></div><button onClick={reset} className="ml-auto text-xs font-semibold opacity-50">Change</button></div>
   <label className="text-sm font-semibold">Application / exam requirement</label><select value={req.id} onChange={e=>apply(REQUIREMENTS.find(r=>r.id===e.target.value)!)} className="mt-2 w-full rounded-xl border border-black/10 bg-white px-3 py-3 text-sm"><optgroup label="India • Student & Exam Forms">{REQUIREMENTS.slice(0,-1).map(r=><option key={r.id} value={r.id}>{r.title}</option>)}</optgroup><option value="custom">Custom Requirement</option></select>
   <div className="grid grid-cols-2 gap-3 mt-4"><div><label className="text-xs font-semibold opacity-60">Minimum KB</label><input type="number" min="0" value={minKB} onChange={e=>setMinKB(Math.max(0,Number(e.target.value)))} className="mt-1 w-full rounded-lg border border-black/10 px-3 py-2"/></div><div><label className="text-xs font-semibold opacity-60">Maximum KB</label><input type="number" min="1" value={maxKB} onChange={e=>setMaxKB(Math.max(1,Number(e.target.value)))} className="mt-1 w-full rounded-lg border border-black/10 px-3 py-2"/></div></div>
   <div className="grid grid-cols-2 gap-3 mt-3"><div><label className="text-xs font-semibold opacity-60">Width px {width?'':'(optional)'}</label><input type="number" min="1" value={width??''} placeholder="Auto" onChange={e=>setWidth(e.target.value?Number(e.target.value):undefined)} className="mt-1 w-full rounded-lg border border-black/10 px-3 py-2"/></div><div><label className="text-xs font-semibold opacity-60">Height px {height?'':'(optional)'}</label><input type="number" min="1" value={height??''} placeholder="Auto" onChange={e=>setHeight(e.target.value?Number(e.target.value):undefined)} className="mt-1 w-full rounded-lg border border-black/10 px-3 py-2"/></div></div>
   <div className="mt-4 rounded-xl bg-black/[.03] px-4 py-3 text-xs"><b>{req.title}</b><br/>{req.minKB?`${req.minKB}–`:''}{req.maxKB?`${req.maxKB} KB`: 'Custom'}{req.width&&req.height?` · ${req.width}×${req.height}px`:''} · {req.format}<br/><span className="opacity-50">{req.note}</span></div>
   <button onClick={run} disabled={stage==='compressing'} className="w-full mt-5 rounded-xl bg-ink text-white font-semibold py-3.5 disabled:opacity-60">{stage==='compressing'?'Making it upload-ready…':'Make Upload-Ready'}</button>
  </div>}
  {stage==='done'&&result&&url&&<div className="rounded-2xl border border-black/10 bg-white/80 p-6 text-left"><div className="grid grid-cols-2 gap-4"><div><p className="text-xs font-bold opacity-50 mb-2">BEFORE</p><img src={url} className="w-full aspect-square object-cover rounded-xl" alt="Before"/><p className="mt-2 text-sm font-semibold">{formatBytes(file!.size)}</p></div><div><p className="text-xs font-bold opacity-50 mb-2">AFTER</p><img src={result.url} className="w-full aspect-square object-cover rounded-xl" alt="After"/><p className="mt-2 text-sm font-semibold">{formatBytes(result.sizeBytes)}</p></div></div><div className={`mt-5 rounded-xl px-4 py-3 text-sm font-semibold ${valid?'bg-green-50 text-green-700':'bg-amber-50 text-amber-700'}`}>{valid?'✓ READY FOR YOUR SELECTED FILE REQUIREMENT':'⚠ Size target could not be fully met without more degradation.'}<div className="font-normal text-xs mt-1">{result.width}×{result.height}px · {formatBytes(result.sizeBytes)} · JPG</div></div>{req.note&&<p className="mt-3 text-xs opacity-50">Note: {req.note}</p>}<div className="flex gap-3 mt-5"><a href={result.url} download={`realimageresizer-${req.id}.jpg`} className="flex-1 text-center rounded-xl bg-accent text-white font-semibold py-3.5">Download</a><button onClick={reset} className="rounded-xl border border-black/15 px-5 font-semibold">Start over</button></div></div>}
 </div>;
}
